# Generated by Django 4.1.2 on 2022-10-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskdeadline',
            field=models.IntegerField(default=123, verbose_name='Dead line'),
            preserve_default=False,
        ),
    ]
